name: Falcon IOA Pipeline

on:
  push:
    branches: [ release ]
    paths:
      - 'crowdstrike/queries/*'
  pull_request:
    branches: [ release ]
    paths:
      - 'crowdstrike/queries/*'

permissions:
  contents: read
  actions: write

jobs:
  generate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./crowdstrike
    steps:
      - uses: actions/checkout@v5
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: crowdstrike/requirements.txt
      - name: Install dependencies
        run: pip install crowdstrike-falconpy>=1.5.2 pyyaml>=6.0.1
      - name: Generate JSONs
        run: python pipeline.py --generate
      - name: Archive JSONs
        uses: actions/upload-artifact@v4
        with:
          name: import-jsons
          path: ./import/
          retention-days: 7

  upload:
    runs-on: ubuntu-latest
    needs: generate
    environment: production
    defaults:
      run:
        working-directory: ./crowdstrike
    steps:
      - uses: actions/checkout@v5
      - name: Download JSONs
        uses: actions/download-artifact@v5
        with:
          name: import-jsons
          path: ./import/
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: crowdstrike/requirements.txt
      - name: Install dependencies
        run: pip install crowdstrike-falconpy>=1.5.2 pyyaml>=6.0.1
      - name: Upload to Falcon
        env:
          FALCON_CLIENT_ID: ${{ secrets.FALCON_CLIENT_ID }}
          FALCON_CLIENT_SECRET: ${{ secrets.FALCON_CLIENT_SECRET }}
          RULEGROUP_ID: ${{ vars.RULEGROUP_ID }}
        run: python pipeline.py --upload --rulegroup_id ${{ vars.RULEGROUP_ID }}